### ISSUE TITLE
Deletion of key from keyvalue doesn't seem to work.

### ISSUE THREAD

**Issue by umayaml** [janelia-flyem/dvid#101]
Ran this curl command
curl -X DEL http://dvid.server:8500/api/node/<uuid>/annotations/key/7772754
and get this response
key endpoint does not support "del" HTTP verb (/api/node/<uuid>/annotations/key/7772754).
Is this broken or am I not using the api call to delete correctly?

**Comment by stephenplaza** [comment]
Try 'DELETE' instead of 'DEL'.  I think it is just a http verb issue.

**Comment by umayaml** [comment]
Ok, that looks like it worked. The help documentation needs to be updated since it says to use DEL.
