### ISSUE TITLE
Allow labelblk put to overwrite existing segmentation

### ISSUE THREAD

**Issue by stephenplaza** [janelia-flyem/dvid#110]
Provide an API that allows one to PUT labelblks so that pre-existing labelblks are read and synced labelvol that conflict are tombstoned properly.

**Comment by DocSavage** [comment]
Steve also wants a query string for labelblk mutations that specify the zero label is "use previous value" instead of background.

**Comment by DocSavage** [comment]
This was completed as of commit 65bdb6cab019367449ed46a24907d1fa8efdad88.
