### ISSUE TITLE
Inconsistency in labelvol and labelblk after split

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/dvid#117]
The node is emdata1.int.janelia.org:8500/api/node/b0f7. The user tried to split body 337366612 into two parts. The request  'POST http://emdata1.int.janelia.org:8500/api/node/b0f7/bodies3/split-coarse/337366612 …' generated a new body 400643074 in labelblk, but failed to return a new body ID. The sparsevol of 400643074 is not generated. The discrepancy can be seen at (3352, 1779, 13125). There was a successful split on 337366612 about two minutes earlier.

**Comment by tingzhao** [comment]
Log details:
INFO  2015-12-08T15:32:17.333 "Processing splits ... "
INFO  2015-12-08T15:32:17.679 "2 labels extracted. "
INFO  2015-12-08T15:32:18.262 HTTP POST:  "http://emdata1.int.janelia.org:8500/api/node/b0f7/bodies3/split-coarse/337366612"
INFO  2015-12-08T15:32:18.542 HTTP POST:  "http://emdata1.int.janelia.org:8500/api/node/b0f7/bodies3/split/337366612?splitlabel=400643073"
INFO  2015-12-08T15:32:18.663 "Label 2 uploaded as 400643073 (1423455 voxels). "

…

INFO  2015-12-08T15:33:59.581 "Processing splits ... "
INFO  2015-12-08T15:33:59.945 "2 labels extracted. "
INFO  2015-12-08T15:34:00.382 HTTP POST:  "http://emdata1.int.janelia.org:8500/api/node/b0f7/bodies3/split-coarse/337366612"
ERROR 2015-12-08T15:34:00.408 ../gui/dvid/zdvidwriter.cpp @ 774 [ uint64_t ZDvidWriter::writePartition(const ZObject3dScan&, const ZObject3dScan&, uint64_t) ] Failed to write coarse split.
ERROR 2015-12-08T15:34:00.427 ../gui/flyem/zproofreadwindow.cpp @ 345 [ void ZProofreadWindow::dump(const ZWidgetMessage&) ] "Warning: Something wrong happened during uploading! Please contact the developer as soon as possible. "

**Comment by DocSavage** [comment]
This was traced to an incorrect block (103, 59, 409) being sent as part of the coarse split when it's not part of the original label (337366612).  Logs show an error message was returned with HTTP status code 400, which is correct if a bad block coordinate was sent.

As long as you are sequentially getting "sparsevol", they should be consistent as soon as you get the response back from a previous POST.  The only time this could be a race condition is if you are using labelblk voxel GETs to figure out how to do subsequent splits.  So I think it's probably a bug on the client side.  Let me know if you think it's still on server side.

**Comment by DocSavage** [comment]
This will be closed for now.  If issue is really on DVID side, please reopen.

**Comment by DocSavage** [comment]
This is being reopened with idea that DVID should always produce consistency between denormalizations even if it is supplied with bad data.  Or else some method should be added that allows resyncing data after the fact.  We could use the DAG here so that if some client error occurs on body split, we can look at the parent version's corresponding body, which should be a superset of all blocks that could be messed up, and run denormalization on just those blocks.

**Comment by DocSavage** [comment]
This prior bug was cause of issue #153.  The artifact could be corrected via appropriate client-side data POSTs.
