### ISSUE TITLE
Synapse off the body

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/dvid#127]
In the node 4ad1 at emdata2.int.janelia.org:7000, the synapse at (7275,4290,13315) is not on the body 32. But synapse query on body 32 (http://emdata2.int.janelia.org:7000/api/node/4ad1/annot_synapse/label/32) contains that synapse.

**Comment by DocSavage** [comment]
Lowell reloaded the synapses after the code fix into the data instance "annot_synapse_021016".  You should be using that instead of annot_synapse.  Let me know if problems exist with that annotations data instance.
