### ISSUE TITLE
Ability to change datatype instance name

### ISSUE THREAD

**Issue by csweaver** [janelia-flyem/dvid#128]

**Comment by DocSavage** [comment]
Modifying the instance name is a problem if the repos have been distributed.  We plan to move to fully immutable metadata, moving any mutable data properties (e.g., extents of stored data) outside of the core in-memory metadata (DAG).

**Comment by DocSavage** [comment]
Currently, data instances are described by a (name, uuid) tuple with the uuid typically implicit in an ongoing operation.  In the future, each data instance should get a UUID that then gets mapped to a name.  This will allow easy changes of names as well as use of the same name in different locations.
