### ISSUE TITLE
Add partitioning capability to DVID key

### ISSUE THREAD

**Issue by tomdolafi** [janelia-flyem/dvid#130]

**Comment by DocSavage** [comment]
For kvautobus (or other storage engines), add a "namespace" component to the key that corresponds to a dataset.  Tom, what should be the granularity of the partition?  I could pass an identifier that corresponds to a repo or data instance (of which there are many within each repo)?

**Comment by tomdolafi** [comment]
Repo level.  Assuming that's the project (data set) level.  Need it granular enough to partition (index) separately, but not too granular causing the need to query multiple partitions (indices).
