### ISSUE TITLE
annotation tag matching

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/dvid#131]
Currently annotation tag query does not perform exact string match. For example, tag/a returns all tags with a.*. It would be nice to have extract string match in some cases like querying with user name.

**Comment by DocSavage** [comment]
I will change default behavior to be exact and then add a query string option `?match=prefix` to allow returns with the current behavior.

**Comment by gbhuang** [comment]
There may be some unexpected behavior with the tag query.  

First, verifying that there are synapses with the tag "Syn427" - http://emdata2:8000/api/node/dd0/combined_synapses_08302016/elements/1_1_1/9193_3743_8987

However, tag query for "Syn427" returns *only* tag "Syn4279" - http://emdata2:8000/api/node/dd0/combined_synapses_08302016/tag/Syn427

Additionally, tag query for "Syn4" returns only tag "Syn4999" - http://emdata2:8000/api/node/dd0/combined_synapses_08302016/tag/Syn4

**Comment by DocSavage** [comment]
This is a bug that will manifest when there are tags sharing the same prefix.  The way I currently implement versioning requires a range query that assumes unique type-specific key prefixes.  Annotation tags can have arbitrary length and shared prefixes, so they get conflated.  Simple solution is to do what I did for keyvalue instance and always append a termination byte (0 byte in this case) that cannot be part of the key/tag.  This would require reloading annotations into production systems, after which the situation should be resolved.

**Comment by DocSavage** [comment]
In particular, this bug surfaces if tags have a common prefix but a different size, so where the tests passed for tags "Synapse1" and "Synapse2", it would have failed if tested against tags "Synapse1" and "Synapse12".

**Comment by DocSavage** [comment]
The fixed version will not include prefix matching.  Rather than add that as query option, I will close this issue and ask if someone wants prefix matching of Tag, add an enhancement request and I'll add that option via the `?match=prefix` query string.
