### ISSUE TITLE
allow 3d request for labelblk that just passes compressed blocks

### ISSUE THREAD

**Issue by stephenplaza** [janelia-flyem/dvid#137]
Currently labelblk supports an endpoint that allows one to ask for a block span in X and returns the compressed blocks directly from the DB.  This endpoint should be changed to allow one to specify the X_Y_Z block spans from the given block starting point.

I don't think anyone is using this endpoint currently so it might be best to just change the endpoint.

**Comment by DocSavage** [comment]
This has been fulfilled by specificblocks endpoint.
