### ISSUE TITLE
philhofer/fwd issue in current master

### ISSUE THREAD

**Issue by unidesigner** [janelia-flyem/dvid#150]
Hi,
FYI, running the dev install on Ubuntu 16.04 with DVID master failed with
`[  5%] Adding msgp messagepack library...
../../../tinylib/msgp/msgp/read.go:9:2: no buildable Go source files in $HOME/go/src/github.com/philhofer/fwd
`
I fixed it by manually cloning https://github.com/philhofer/fwd in the respective directory and it compiled fine.

**Comment by DocSavage** [comment]
Yes, there is occasional issue of git submodules or "go get" not working automatically.  We will be fixing this shortly by moving all vendored packages into the main dvid repo so there are no external dependencies anymore, at the cost of code bloat in the main repo.

**Comment by unidesigner** [comment]
Ok, strange that this happens.
