### ISSUE TITLE
Configuring DVID error

### ISSUE THREAD

**Issue by GBWen** [janelia-flyem/dvid#154]
Hello! 
When I configure dvid using simple example configuration files.It says " Unanle to initialize datastore:Error loading metadata:Error loading new local ids:Bad value returnedfor new ids.Length 0 bytes!" 
The store path I use the generated leveldb of  compiled dvid . Is it error?  Where is or How can I get metadata? Thanks!

**Comment by DocSavage** [comment]
Hi, this was an error that occurred in earlier versions when there was an empty directory for database, so let me know how you built or downloaded dvid (what version).  You should be able to use the recent compiled tarballs in the release area: https://github.com/janelia-flyem/dvid/releases/tag/v0.8.2

**Comment by GBWen** [comment]
Hello!
Dvid about says:dvid version  v0.8.1-41-gb16ca and datastore version 0.10.0 and storage engines
 basholeveldb;kvautobus
I installed dvid by developer installation. The store path is /buildem/src/basholeveldb-1.9.
Is it error?
Thank you !

**Comment by GBWen** [comment]
I download v0.8.2 and it works thank you!_(:з」∠)_
