### ISSUE TITLE
synapse syncing problem

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/dvid#157]
In the mushroom body dataset (node 2ed9 on emdata1), the tbar at  (4609, 4036, 12038) is on body 2949607, but it can be also queried by the body ID 3878341. In other words, the request on http://emdata1.int.janelia.org:8500/api/node/2ed9/mb6_synapses/label/3878341 returns a list of synapses that contains the tbar at  (4609, 4036, 12038), which is actually on the body 2949607.

**Comment by DocSavage** [comment]
If you have any context on what ops happened to that body, it would be helpful in the debugging.

**Comment by DocSavage** [comment]
One issue is that there are multiple syncs on the "mb6_synapses" annotations instance.   Not sure how it happened but we have:

"Syncs": ["labels3", "bodies3", "labels3", "bodies3"]

This might not matter.  Looking through code to see.

**Comment by DocSavage** [comment]
Looks like my code makes sure only one subscription exists for any particular event, although it could launch additional goroutine handlers.  So should make sure it's cleaner but probably not the cause of any error.

**Comment by tingzhao** [comment]
Another potential syncing error on FIB19:

The annotation was deleted at 12:36:40 today by sending the del request to http://emdata2.int.janelia.org:7000/api/node/3c25/segmentation-labelvol_todo/element/4726_5474_5660. But it can still queried by body 238.

**Comment by DocSavage** [comment]
Ting, when you say "the tbar at (4609, 4036, 12038) is on body 2949607", is that determined by looking at the "labels3" underneath that tbar position?  When querying the mb6_synapses annotation for node 2ed9, that tbar is in body 3878341 but it is NOT in body 2949607.

Do you have any idea of the sequence of operations involving these two bodies?
