### ISSUE TITLE
Dead links in API help pages

### ISSUE THREAD

**Issue by grisaitis** [janelia-flyem/dvid#161]
I encountered a broken link in the API help page for the multichan16 data instance type (`/api/help/multichan16`). The doc starts with:

> API for datatypes derived from multichan16 (github.com/janelia-flyem/dvid/datatype/multichan16)

But sadly [github.com/janelia-flyem/dvid/datatype/multichan16](github.com/janelia-flyem/dvid/datatype/multichan16) is broken :crying_cat_face: 

I'm not sure if any other link references are broken as well

**Comment by DocSavage** [comment]
That's a reference to the Go package that implements multichan16, not a http callable help page.  The rest of that API help page should be correct.
