### ISSUE TITLE
Timeout response error on RPC

### ISSUE THREAD

**Issue by unidesigner** [janelia-flyem/dvid#165]
With
 ```dvid -rpc=:8041 node 5b grayscale load 0,0,0 "/path/to/my/*.tif"```

I get a timeout error

```2016/06/21 16:34:14 gorpc.Client: [:8041]. Cannot obtain response during timeout=20s
RPC error for "node 5b grayscale load 0,0,0 /path/to/my/*.tif": gorpc.Client: [:8041]. Cannot obtain response during timeout=20s```

but looking at the log, DVID started to ingest images one-by-one in the background. 

@DocSavage responded with: This occurred when I went from the old builtin Go rpc library to the more optimized gorpc package. It shouldn't affect the load command.

**Comment by huanxiang** [comment]
I am running the docker image and I got the same error when creating the tiles:

`root@73e27c649826:/data/logs# dvid -stdin node 17 mytiles2 generate planes=xy < /dvid_data/test.json `

It created the tiles for the first dozens of slices but not the rest.
```
2016/06/27 15:44:03 gorpc.Client: [localhost:8001]. Cannot obtain response during timeout=20s
RPC error for "node 17 mytiles2 generate planes=xy": gorpc.Client: [localhost:8001]. Cannot obtain response during timeout=20s
```

Any idea?

Thanks!

**Comment by DocSavage** [comment]
The timeout is something I should fix, but I'm surprised it halted the tiling.  Didn't tiling continue to occur even though you got this timeout?

**Comment by DocSavage** [comment]
@huanxiang If you are still getting a hangup of the tile generation, then it's a separate issue than the timeout, which should now be fixed.  If so, run dvid in "-verbose" mode and paste in the log when the tile generation begins.  Thanks!
