### ISSUE TITLE
Allow user to specify meta description of data being stored

### ISSUE THREAD

**Issue by stephenplaza** [janelia-flyem/dvid#173]
In addition to typename, it would be nice to have a description field for what that data is.  For key values this could be useful to identify sub-types.  Any keyvalue that stores skeletons could be called 'skeletons' for instance.

**Comment by DocSavage** [comment]
Could add a "note" field similar to what we do for repo versions.

**Comment by DocSavage** [comment]
This can now be handled using Tags set during creation of data instance.  See commit 94577a
