### ISSUE TITLE
Slow annotation reading

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/dvid#180]
Example:
The request of getting
http://emdata1.int.janelia.org:7000/api/node/3e17/annot_synapse_083116/elements/256_32_256/6738_6752_11133
takes about 5 seconds.

**Comment by DocSavage** [comment]
Could you give me an idea of what the same synapse volume would take if oriented along XY?  And also how many synapses are returned in the XY vs XZ case?  This would help me determine the main issue (too many seeks vs serialization / data size, etc.)  Thanks.

**Comment by DocSavage** [comment]
Issue marked resolved due to other optimizations.
