### ISSUE TITLE
Add API request to ask if node is unlocked/locked

### ISSUE THREAD

**Issue by umayaml** [janelia-flyem/dvid#184]
It would be helpful if I could submit a node uuid to DVID and it return 1 for unlocked and 0 for locked. That way I don't need to  parse the repo info to get this information.

**Comment by DocSavage** [comment]
OK, this will be new API endpoint:

  GET /api/node/{uuid}/commit

    Returns the commit or lock state of the node with given UUID in JSON format:

	{ "Locked": true }
