### ISSUE TITLE
labelsz top 0 gives 500 error

### ISSUE THREAD

**Issue by olbris** [janelia-flyem/dvid#187]
Hitting the "top" endpoint for labelsz with n = 0 results in a 500 server error. Should probably return empty list instead.

Example: http://emdata1.int.janelia.org:7000/api/node/3b548cfb0faa4339bb09f2201bd68fd9/annot_synapse_08162016_labelsz/top/0/AllSyn

Stumbled on while debugging bad code. Fix would be for "least surprise" purposes, not actual use case.

**Comment by DocSavage** [comment]
Yes, that DVID server emailed me on the rude API request and its subsequent panic :)
