### ISSUE TITLE
hostname not displayed properly in error message

### ISSUE THREAD

**Issue by olbris** [janelia-flyem/dvid#190]
I stumbled across this by calling a wrong API in the browser. I called http://emdata2.int.janelia.org:8000/api/node/eddf/bodies3_todo/keys and got the message "Bad API call (/api/node/eddf/bodies3_todo/keys) for data "bodies3_todo".  See API help at http://localhost:8000/api/help/annotation". Note that "localhost" appears in the message instead of the actual server name. 

Low(est) priority. I expect that fixing this bug will save less time in the future than it took me to write out this report, which leads me to wonder about the choices I'm making. However, knowing the bug is documented will help me sleep better, so that's an upside.

**Comment by DocSavage** [comment]
For that particular dvid server (emdata2:8000), the TOML file sets the `httpAddress = ":8000"`.  So from dvid's perspective, it is localhost:8000 and outside of dvid, we redirect any emdata2 port 80 calls to the localhost port 8000.

I think the real question is whether we should have a host alias in the configuration and give that for HTTP help messages.  At most, dvid would be able to use the hostname "c06u30.int.janelia.org" but it will be unable to divine we really call that server via an alias "emdata2".
