### ISSUE TITLE
username/app name stuff not documented in help pages

### ISSUE THREAD

**Issue by olbris** [janelia-flyem/dvid#192]
The ability to add a user and application name to the URL (u= and app=) does not appear to be documented. I think I'd expect to see it on the /api/help page. I had to check libdvid source to find the syntax.

**Comment by DocSavage** [comment]
Right now dvid doesn't do anything with those query strings.  At some point it would be superseded by a token-based authentication system, so it's a convention we've established outside of dvid to notate requests so we can determine callers from the logs.
