### ISSUE TITLE
Check labelsz setting ROI to see if it restricts to the roi

### ISSUE THREAD

**Issue by umayaml** [janelia-flyem/dvid#202]
Ting/Kazunori have reported that the labelsz that were recently created that were restricted to ROI still show the full list of bodies and synapses for the entire volume. labelsz data instances in question:
http://emdata2.int.janelia.org:7000/api/node/e2f02a7f4d71409cb693f4af06febaca/annot_synapse_010417_ROI_LOP_15/info
http://emdata2.int.janelia.org:7000/api/node/e2f02a7f4d71409cb693f4af06febaca/annot_synapse_010417_ROI_LOP_40/info
Both synced to http://emdata2.int.janelia.org:7000/api/node/e2f02a7f4d71409cb693f4af06febaca/annot_synapse_010417/info
Could the ROI/uuid being set on labelsz not being recognized thus the data instance is reporting everything?

**Comment by DocSavage** [comment]
@umayaml Just to clarify how these data instances were setup:

1) annot_synapse_0_10417 was pre-existing and synced to segmentation2 (labelblk) and segmentation_labelvol (labelvol) instances.
2) the new labelsz instances were created with the ROI as part of creation and synced to annot_synapse_0_10417 at that time.
3) you did a POST /reload on the annotation instance.

Was that the exact sequence of operations?

**Comment by DocSavage** [comment]
This looks to be a problem with the new /reload endpoint not forcing a full recalculation on synced instances.  Working on a fix.
