### ISSUE TITLE
Build error with gbucket backend

### ISSUE THREAD

**Issue by grisaitis** [janelia-flyem/dvid#205]
Hi! I'm getting an error when trying to `make dvid`. It tries find a directory that doesn't exist: `$HOME/go/src/github.com/golang/protobuf/{proto,protoc-gen-go}`. 

Do you think this an issue with a dependency version, or how make / cmake is working, or..?

```
...
Scanning dependencies of target context
[ 89%] Adding go.net context
[ 89%] Built target context
Scanning dependencies of target gcloud
[ 91%] Adding gcloud packages...
package github.com/golang/protobuf/{proto,protoc-gen-go}: invalid github.com/ import path "github.com/golang/protobuf/{proto,protoc-gen-go}"
CMakeFiles/gcloud.dir/build.make:57: recipe for target 'CMakeFiles/gcloud' failed
CMakeFiles/Makefile2:1048: recipe for target 'CMakeFiles/gcloud.dir/all' failed
make[3]: *** [CMakeFiles/gcloud] Error 1
make[2]: *** [CMakeFiles/gcloud.dir/all] Error 2
make[1]: *** [CMakeFiles/dvid.dir/rule] Error 2
CMakeFiles/Makefile2:1155: recipe for target 'CMakeFiles/dvid.dir/rule' failed
Makefile:547: recipe for target 'dvid' failed
make: *** [dvid] Error 2
/bin/sh: 1: cd: can't cd to /go/src/google.golang.org/cloud
fatal: Could not parse object '8bc2457bef5a52c10b0001d481d441141095b130'.
can't load package: package github.com/janelia-flyem/dvid/build: no buildable Go source files in /go/src/github.com/janelia-flyem/dvid/build
[  2%] Adding go package dependencies for janelia-flyem projects...
[  2%] Built target gopackages-install
[  5%] Updating required Go packages...
[  5%] Built target gopackages
...
```

**Comment by DocSavage** [comment]
CircleCI auto-builds off the repo seem to work and are also Ubuntu.  Could you paste the actual sequence of commands you use from the beginning?  Presumably you are using approach from the User Guide: https://github.com/janelia-flyem/dvid/wiki/Developer-Installation

**Comment by DocSavage** [comment]
Just forced a clean rebuild on CircleCI and it was successful so doesn't seem like it's a Go package not being available any more.

**Comment by grisaitis** [comment]
What's the `DVID_BACKEND` option given for the CI platforms, for `cmake`?

The issue happens if I include `gbucket` in `DVID_BACKEND`, and not if I exclude it. 

I was using the [Dockerfile provided at janelia-flyem/flyem-dockerfiles](https://github.com/janelia-flyem/flyem-dockerfiles/blob/master/dvid/Dockerfile).

I eventually made my own dockerfile which seems to work just fine and has fewer commands:

```
FROM golang:1.7.5
MAINTAINER William Grisaitis <grisaitisw@janelia.hhmi.org>

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    mercurial \
    zip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR $GOPATH/src/github.com/janelia-flyem/dvid
RUN git clone https://github.com/janelia-flyem/dvid . \
    && git checkout 6b5bb3adac2486a57567d7901eae9648677ce123

WORKDIR $GOPATH/src/github.com/janelia-flyem/dvid/build
ENV BUILDEM_DIR /opt/buildem
RUN cmake -D DVID_BACKEND="basholeveldb;gbucket" -D BUILDEM_DIR=$BUILDEM_DIR ..
RUN make
RUN cmake -D BUILDEM_DIR=$BUILDEM_DIR ..
RUN make dvid

ADD config.toml /var/config.toml
ENV LD_LIBRARY_PATH $BUILDEM_DIR/lib:$LD_LIBRARY_PATH
ENV PATH /usr/local/go/bin:$BUILDEM_DIR/bin:$PATH
CMD "dvid serve /var/config.toml"
EXPOSE 8000

ENV CONSOLEVERSION 1.14.6
RUN wget https://github.com/janelia-flyem/dvid-console/releases/download/v${CONSOLEVERSION}/dvid-console-${CONSOLEVERSION}.tar.gz \
    && tar -C /usr/local -xzf dvid-console-${CONSOLEVERSION}.tar.gz
```

**Comment by DocSavage** [comment]
@grisaitis So I'm now doing builds using gbucket with basholeveldb tags and have no problems.  There can be issues if you've done past builds of dvid where older go packages exist, particularly those dealing with gcloud.  When building dvid, you can do the following:

    % GO_GET=-u make dvid

The above `GO_GET=-u` forces updates on the dependent go packages.
