### ISSUE TITLE
Change `dvid repos delete <uuid>` to only delete the node defined by uuid

### ISSUE THREAD

**Issue by grisaitis** [janelia-flyem/dvid#209]
Specifying `dvid repos delete <UUID>` currently deletes the root of `UUID`. 

Proposed behavior changes:
1. only accept root UUIDs. If `UUID` is not a root node, then return an error
2. only delete the node of the UUID (and anything beneath it)

I would expect behavior 2.

**Comment by DocSavage** [comment]
The current command is to delete a repo, not a subset, so proposed behavior change 1 is a reasonably safe guard while change 2 requires additional work and new functionality.  We are going with 1.
