### ISSUE TITLE
labelsz not synced to annotation

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/dvid#221]
http://emdata2.int.janelia.org:7000/api/node/e2f0/annot_synapse_010417_labelsz/count/131185739/PostSyn
returns a count that's inconsistent with
http://emdata2.int.janelia.org:7000/api/node/e2f0/annot_synapse_010417/label/131185739

**Comment by DocSavage** [comment]
labelsz is being deprecated since size is built into labelmap.  So will not investigate this particular case.
