### ISSUE TITLE
Add simple log to labelarray

### ISSUE THREAD

**Issue by stephenplaza** [janelia-flyem/dvid#225]
When labelarray enables indices and supports merge/split, there should be a simple log system that will save the merge and split history.  The split history can be saved just as  " body B -> B and B' " -- the exact split voxels do not need to be recorded.  This log will be versioned.

It should be possible to view merge / split history by querying a REST API.  The API should allow querying of operations either by version or across entire ancestry.

**Comment by DocSavage** [comment]
This has been partially implemented.  There is no REST API but there is a mutation log capability that can be assigned to any datatype that can use it.

**Comment by DocSavage** [comment]
Labelarray mutations are now logged to kafka and merge/split history can be done through consuming those messages with the appropriate topic.  Added commit b1c69ec.
