### ISSUE TITLE
Crash when new instance uses compression: none

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#241]
I want to create a keyvalue instances to store draco-encoded meshes.  Since that format is compressed already, there is probably little benefit to compressing it again within DVID's internal storage.  Therefore, I attempted to disable compression when the instance was created:

```python
uuid = '244f9550'
r = requests.post(f'http://emdata3:8000/api/repo/{uuid}/instance',
                  json={ "typename": "keyvalue",
                         "dataname": "my-new-instance",
                         "compression": "none" })
```

That crashed the repo, apparently.

**Comment by DocSavage** [comment]
Was unable to reproduce the error on emdata3, and I added some unit tests (uncommitted yet) that weren't able to cause whatever issue happened.
