### ISSUE TITLE
Actions on command line vs. API

### ISSUE THREAD

**Issue by rivo** [janelia-flyem/dvid#248]
Apologies if these questions are very basic but I can't find the answers anywhere myself. I'm using the official DVID Docker image.

__(1)__ How do I delete a repo from the command line? I'm following the [Simple Example instructions](https://github.com/janelia-flyem/dvid/wiki/Simple-Example) as well as the commands found [here](https://github.com/janelia-flyem/dvid/blob/master/server/rpc.go) but I'm getting the following:

```
$ dvid repo c8 delete grayscale
RPC error for "repo c8 delete grayscale": Unknown command: "repo c8 delete grayscale"

$ dvid repos c8 delete
RPC error for "repos c8 delete": Unknown repos command: "c8"
```

Is there no "delete" command in the Docker version? Using the API to DELETE a repo works fine.

__(2)__ Is there an API equivalent for the "load" command? How can I load PNG files into a repository using the API?

**Comment by DocSavage** [comment]
Sorry for the delay in answering.  For (1), if you see something like "Unknown command" it's likely that the command is missing a key string.  In your first command I'm not sure what's going on.  I'll check to see if the docker image is older than that command.  For (2) you've reversed the order of the last two fields since it expects `dvid repos delete c8` per the command documentation.

**Comment by rivo** [comment]
Should the "load" command still work in the latest version? (It actually crashes my build, see #249.) My task is to add a new storage backend to DVID so I'm not using any sophisticated tools in front of DVID. Basically, I need something simple to test the storage and "load" seemed pretty good for that purpose. Or would you recommend doing something else? (I guess using /raw will require me to somehow chop up my PNGs myself, I wonder if I can get around that.)

**Comment by DocSavage** [comment]
The load should work ok.  As I mentioned in the closed issue, you could specify a different form of compression for the uint64 data instance you are using for your images, say uncompressed (if you don't care about size) or gzip (if you are concerned about size but less about speed).

**Comment by rivo** [comment]
Thanks. Will do.
