### ISSUE TITLE
Delete CMakeLists.txt

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#254]
Dvid's old BuildEM-based build build system is now deprecated in favor of using conda and a a simple `Makefile`, as explained in [`GUIDE.md`][1].  The old `CMakeLists.txt` file should be deleted.  It is strange for a code base to have both a `CMakeLists.txt` and `Makefile`.

The only thing preventing us from doing this right now is the CI setup, which depends on `CMakeLists.txt`.

[1]: https://github.com/janelia-flyem/dvid/tree/master/GUIDE.md

**Comment by DocSavage** [comment]
Well, and the dvid creator who clings to buildem due to lethargy :)  We should make the switch...

**Comment by DocSavage** [comment]
@stuarteberg Would it be possible to handle issue #251 and related issues by using conda build with appropriately old glibc even on newer Ubuntu builds?

**Comment by stuarteberg** [comment]
Yesterday, I built the new binary packages within a docker container with a fairly old OS (CentOS-6).  The binary distribution ought to be capable of running on newer Ubuntu builds.  Is that what you mean?

(BTW, I added some basic instructions for the Docker build in GUIDE.md.  The process could certainly be streamlined, though.)
