### ISSUE TITLE
REST endpoint for GET /mappings

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#257]
Similar to the command-line API that exists already:

```
dvid node <UUID> <data name> dump <dump type> <file path>
```

CSV should suffice for the REST endpoint, too.

But if you want to use protobuf, that's okay. (We already have the necessary structure defined for the `POST` `/mappings`, so it won't be much work for me to use that code.)

Side note: Most people use `,` as the delimiter in CSV files...

**Comment by DocSavage** [comment]
I've updated the documentation for "dump" to reflect it's a space-delimited file if saying CSV leads people to expect commas.  In order for the REST endpoint to coincide with the dump command, it will also give space-delimited values.
