### ISSUE TITLE
Validate inputs to /mapping

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#265]
As discussed in today's software meeting, it would be nice if the `/mapping` endpoint fails when a non-existent supervoxel is given as the input.  Similarly, the bulk `/mappings` endpoint should not return supervoxels that no longer exist in the volume (e.g. due to splits).

If performance is a concern, the `/mapping` endpoint could support query string flag which, if set, tells DVID to assume that the input supervoxels are valid, and thus there is no need to verify their validity.  However, please make the default behavior "safer but slower" -- i.e. check the client's inputs.

**Comment by DocSavage** [comment]
Rather than have /mapping completely fail, since it is a batch query, non-existant supervoxels will return a zero label to indicate it no longer exists.
