### ISSUE TITLE
tarsupervoxels bugs

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#272]
I've observed the following issues with the hot-off-the-presses `tarsupervoxels` endpoint:

1. When I create a `tarsupervoxels` instance while using the `basholeveldb` backend, I can post and read data.  But using the `filestore` backend, no data is actually stored.  Attempting to retrieve a key results in an error, such as:

    ```
    Error in retrieving supervoxel 14634755: open /magnetic/dvid-filestore/40/f8/b130/v84-i437-8501034fdf0000000000: no such file or directory (/api/node/3c0954d5534f4880a840ee937016ca73/labels_sv_meshes/supervoxel/14634755).
    ```

    Indeed, though the appropriate directory was created (`.../dvid-filestore/40/f8/b130`), it contains no files.

2. When using the `basholeveldb` backend, I can store data and retrieve it using the `/supervoxel` endpoint.  However, there are two minor problems with the `/tarfile` endpoint:
   - The files have extension `.dat` instead of the extension I stored them with (e.g. `.obj` or `.drc`)
   - The files have the wrong file permissions, as if someone used `chmod 000` to set the permissions.  That is, I can't even read the file until I change the permissions.

**Comment by DocSavage** [comment]
First issue should be resolved by commit 4e08e.
Will look into second.
