### ISSUE TITLE
add body-specific mutation id to labelmap

### ISSUE THREAD

**Issue by DocSavage** [janelia-flyem/dvid#286]
This would add an endpoint to labelmap data type that returns a uint64 giving an ID that changes upon every mutation to that particular body.  Ting suggested this enhancement since it would help figure out if denormalizations like skeletons or meshes, data managed by processes external to DVID and not under the dvid sync pub/sub, needs to be updated.  Presumably the external processes would record the body-specific ID on creation of the mesh or skeleton and know if it were stale by asking DVID what that ID is for a particular version.

**Comment by stuarteberg** [comment]
I think this can be closed.

**Comment by DocSavage** [comment]
A superset of this issue was handled through the addition of labelmap's `GET /mutations` endpoint.  The mutation ID is also available through kafka if enabled.

**Comment by stuarteberg** [comment]
And `GET /lastmod`
