### ISSUE TITLE
Add topicprefix to /api/server/info

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#292]
As a result of 97f70bc28999617dfefd23b8192b4cc0fc77d4b5 and 1b5f82e83f47788b0e56c49d0290d001caf8e8d1, the formula for choosing kafka topic names now depends on a field from the TOML file: `topicprefix`.  Therefore, clients who wish to read kafka logs need a way to obtain the `topicprefix` from DVID.

As far as I can tell, `/api/server/info` does not list the `topicprefix`.  Can you expose it?

Alternatively, it might be a bad idea to simply provide access to the entire TOML file via a new endpoint like `/api/server/toml` or something like that.

**Comment by DocSavage** [comment]
There is now a field `"Kafka Activity Topic"` that will be empty string if not set or the string.  Just like `"Kafka Servers"` these fields will only show up if kafka servers are configured.
