### ISSUE TITLE
What is the formula for kafka topic names?

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#293]
I have a question about the listed `RepoUUID` for a particular data instance.

Have a look at the info for `segmentation_todo`:
`http://emdata3:8900/api/node/28841c8277e044a7b187dda03e18da13/segmentation_todo/info`
The `RepoUUID` is listed as `4ea3bd5698204089b82408c178fe1d55`
But that is not the root node for the production repo.
(The root node is `a776af0b132f44c3a428fe7607ba0da0`)
Is that expected?
The weird thing is that the kafka server lists TWO different topics for this instance.  Well, three if you count the `hemiMirror` topic:

`dvidrepo-a776af0b132f44c3a428fe7607ba0da0-data-1e76b4afa159488b836a828afe772d86`
`dvidrepo-4ea3bd5698204089b82408c178fe1d55-data-1e76b4afa159488b836a828afe772d86`
`hemiMirror-dvidrepo-a776af0b132f44c3a428fe7607ba0da0-data-1e76b4afa159488b836a828afe772d86`

However, `dvidrepo-4ea3bd5698204089b82408c178fe1d55-data-1e76b4afa159488b836a828afe772d86` contains no messages.

Looking at other data instances, I guess the `RepoUUID` is defined as "the first node in which this data instance appeared"?
But the KAFKA topic is defined using the ROOT node for the repo, regardless of the instance's declared `RepoUUID`?
Is that the rule?

**Comment by DocSavage** [comment]
If you are using a kafka with topic creation ON you could potentially create an empty topic by querying it I think.
