### ISSUE TITLE
/mappings endpoint should include 'retired' SV ids (mapped to 0)

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#297]
Thanks to the changes implemented for #275, the `/mappings` endpoint never includes supervoxels which no longer exist.  However, it would be nice if it DID include them, and listed them as mapped to body `0`.

Additionally, it would be convenient if cleave body IDs were listed as "supervoxels" in the mapping (also mapped to 0), even though they are not (and never were) supervoxels.

Alternatively, if the mapping were "complete" (i.e. included identity rows for all non-singleton bodies), that would be a convenient, and would obviate my need for cleave bodies  Ideally, I would like all of the above, which would eliminate my need to read the kafka log(s) just to construct a complete mapping for the volume.

Previously, I could augment the mapping with those rows myself, using the kafka logs.  But now that our production kafka log does not include mutations before node `2884`, I can't easily determine "retired" supervoxel IDs without digging up the old kafka log.

**Comment by DocSavage** [comment]
Should be resolved with closing of issue #361.
