### ISSUE TITLE
Add http API for checking if a key exists

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/dvid#304]
Currently I have to use `GET <api URL>/node/<UUID>/<data name>/key/<key>` to check if a key exists, which is time consuming for a key mapped to a heavy value.  Supporting HEAD method or something like `GET <api URL>/node/<UUID>/<data name>/haskey/<key>` can solve the problem.

**Comment by DocSavage** [comment]
The github formatting ate your markdown.  Could you try again?
