### ISSUE TITLE
bulk count endpoint for labelsz

### ISSUE THREAD

**Issue by olbris** [janelia-flyem/dvid#306]
We'd like a bulk "count" endpoint for labelsz. This call would be used when populating the sequencer; instead of making two calls per line in the table (potentially 100k calls or more), only two total calls would be required. Suggested form:

`GET <api URL>/node/<UUID>/<data name>/counts/<index type>`

Note "counts" is plural. `<index type>` is the same as individual GET call (eg, PostSyn, AllSyn, etc).

The body of the request will contain a json list of labels. Return value should be like the /top endpoint: [ { "Label": 188,  "PreSyn": 81 }, { "Label": 23, "PreSyn": 65 }, { "Label": 8137, "PreSyn": 58 } ]

**Comment by DocSavage** [comment]
@olbris I think the formatting got lost in translation...

**Comment by olbris** [comment]
You are correct--Markdown tried to interpret the special characters. Fixed.
