### ISSUE TITLE
Need GET /indices

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#309]
I can post many label indexes at once via `POST .../indexes`, but I can't GET many label indexes at once.  When copying all label indexes from one database to another, fetching them one at a time is slow.  The copy I'm performing right now (using 1-by-1 GET and batched POST) is going to take 8 hours, whereas with batch GET I think it ought to take ~1 hour or less.

**Comment by DocSavage** [comment]
I was thinking we would've wanted a streaming GET but error conditions like too large a return payload (> 2 GB) can't really be returned once data is coming back in HTTP.  So I suggest you specify a JSON array of a number of labels and I return a protobuf for repeated label indices like we currently do for POST /indices.  If you ask for too many labels and the cumulative size is greater than some threshold, I return an error.  Sound OK?

**Comment by stuarteberg** [comment]
Sure
