### ISSUE TITLE
Low-res 3D body viewer

### ISSUE THREAD

**Issue by stephenplaza** [janelia-flyem/dvid#31]
There should be a low-resolution version of the sparse volume viewer that will render typical cell shapes in a fraction of a second.  The denormalizations supporting this viewer should be updated efficiently when label merges are performed.

Two sub requirements:

a)  The client should be able to specify a bounding box (often just a plane) that will be display in the viewer.

b)  The user should be able to retrieve rough x,y,z coordinates by picking locations on the body.

It would be good to have this ready within the next few weeks, but the slower viewer is probably tolerable for now.

**Comment by DocSavage** [comment]
sparse-coarse endpoint was added to labelvol types to enable the viewer.  Since the viewer isn't part of DVID proper, closing this issue here.
