### ISSUE TITLE
Handle missing mutation log settings in the toml

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#313]
If the user's `toml` file does not specify a location for the mutation log, `labelmap` instances don't behave correctly (after restart).  DVID should either provide a suitable default value for the missing toml settings, or (my favorite option) fail to start, and complain to the user about the bad toml settings.

If you choose a default location for the mutation log, how will you know which directory to choose?  The user's activity `logfile` directory is probably not the right choice, and neither is the leveldb database directory...

**Comment by DocSavage** [comment]
Fixed as of commit f6bfdc8.  The labelmap instances must have a "log" system available and will return an error on server startup or an attempt to create a new labelmap if no log is specified.  Documentation for the TOML files have been updated to reflect this.
