### ISSUE TITLE
Expose toml contents and location via http

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#319]
Currently, if I'm curious about how a given DVID server is configured, I have to ssh into the machine where it's running, figure out where the toml file is located (not always easy), and inspect it.

It would be nice if DVID exposed an endpoint such as `.../api/server/config` or `.../api/server/toml` which returns the complete `toml` file contents (including comments, etc.), and also showed the filepath to the `toml` file (say, as a comment inserted at the top of the file).

**Comment by stuarteberg** [comment]
@DocSavage Can we bump the priority of this, BTW?  Is it easy to implement?

**Comment by DocSavage** [comment]
The DVID server can return the TOML file location and contents, but under docker swarm the actual TOML location can be aliased so it's not the true path. For non-containerized DVID servers, the location should be correct.  I'll add TOML file location to `api/server/info` endpoint and the TOML contents itself in a new `api/server/config` endpoint.
