### ISSUE TITLE
Handle the OPTIONS method properly from http requests

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/dvid#324]
Sending POST/PUT/DELETE to DVID from a different website such as neuroglancer may trigger a preflight request, which sends an OPTIONS request to DVID to check if the actual method is available. It appears that DVID will return an error for any OPTIONS request, keeping neuroglancer from writing data to DVID.

**Comment by DocSavage** [comment]
There already is an automatic options middleware as well as CORS handling where "Access-Control-Allow-Origin" is "*".  Is this not an OPTIONS issue but something else?

**Comment by DocSavage** [comment]
Possible issue: https://stackoverflow.com/questions/39286997/google-chrome-a-wildcard-cannot-be-used-in-the-access-control-allow-origin

**Comment by DocSavage** [comment]
Options handling was already being handled.  Handling of CORS was finished as of commit 766cd10f, which permits neuroglancer support.
