### ISSUE TITLE
Permit invalid body IDs when fetching /indices

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#327]
Follow-up to #309 

Now we have an endpoint for `GET .../indices`, but it's a little inconvenient for my use-case because sometimes I don't know if the all of the bodies in my list still exist.

Right now, `.../indices` fails if any one of the bodies in the list is not a valid body ID.  Instead of failing, I'd prefer it if the ones that couldn't be found are simply omitted from the results.  I can check for missing results on my end.  Even if some aren't valid (any more) I'd still like to receive the indices for the others without resorting to the 1-by-1 method (`GET .../index`).

**Comment by DocSavage** [comment]
Non-existent labels will still return an index entry where the Label field is set appropriately but it will have no Blocks and zero-values for other fields.  Fixed in commit 8833c74.
