### ISSUE TITLE
Modify labelmap kafka log for mutations to segmentation to include voxel size

### ISSUE THREAD

**Issue by umayaml** [janelia-flyem/dvid#333]
Update the labelmap kafka log to show the voxel size for each Neuron after it is mutated. One way to relay this information in the Kafka logs is to post the updated Neuron sizes when you log that the mutation has bee completed. (Ex. split-complete, merge-complete, cleave-complete) for all bodies involved in the mutation.

**Comment by DocSavage** [comment]
So this doesn't have to be for all mutations (like voxel-level changes via POST /raw) but only via split, merge, and cleave, right?

**Comment by DocSavage** [comment]
Fixed in commit 12d6cac
