### ISSUE TITLE
Annotation kafka logging for mutations. All merges record a MutationID of 0

### ISSUE THREAD

**Issue by umayaml** [janelia-flyem/dvid#334]
Annotation data instance kafka logging for mutations. All merges record a MutationID of 0.
Example

`{"Action": "merge", "Delta": {"Add": [{"Label": 298599672, "Kind": "PostSyn", "Pos": [25034, 29665, 18955]}, {"Label": 298599672, "Kind": "PostSyn", "Pos": [25041, 29749, 19069]}, {"Label": 298599672, "Kind": "PostSyn", "Pos": [24909, 28375, 16770]}, {"Label": 298599672, "Kind": "PostSyn", "Pos": [24911, 28415, 16809]}, {"Label": 298599672, "Kind": "PostSyn", "Pos": [24940, 28492, 16927]}, {"Label": 298599672, "Kind": "PostSyn", "Pos": [24933, 28532, 16981]}, {"Label": 298599672, "Kind": "PostSyn", "Pos": [25049, 29587, 18878]}], "Del": [{"Label": 1357597410, "Kind": "PostSyn", "Pos": [25034, 29665, 18955]}, {"Label": 1357597410, "Kind": "PostSyn", "Pos": [25041, 29749, 19069]}, {"Label": 1201399884, "Kind": "PostSyn", "Pos": [24909, 28375, 16770]}, {"Label": 1201399884, "Kind": "PostSyn", "Pos": [24911, 28415, 16809]}, {"Label": 1201399884, "Kind": "PostSyn", "Pos": [24940, 28492, 16927]}, {"Label": 1201399884, "Kind": "PostSyn", "Pos": [24933, 28532, 16981]}, {"Label": 1201399884, "Kind": "PostSyn", "Pos": [25049, 29587, 18878]}]}, "MutationID": 0, "Timestamp": "2019-11-12 17:06:40.534659781 -0500 EST m=+234621.621360325", "UUID": "f2cad8c5ff4341ddbb27ac4dcbe06034"}`

**Comment by DocSavage** [comment]
Fixed with commit 4881d6.
