### ISSUE TITLE
Issuing DELETE and POST to DVID keyvalue not going through

### ISSUE THREAD

**Issue by umayaml** [janelia-flyem/dvid#338]
On our production hemibrain server, noticing weird issues yesterday with the focused_assign keyvalue where when I issue api call to DELETE a keyvalue it gets ignored and keyvalue remains. Also seeing when I issue a POST to the keyvalue that it also gets ignored and the new value is not posted. POST errors happened around Dec 5 14:40 to  Dec 5 14:41.

**Comment by stuarteberg** [comment]
@umayaml Found the issue.  It turned out to be in the client code.

**Comment by DocSavage** [comment]
This does seem to be resolved on the client side.
