### ISSUE TITLE
Back-end for clio store body annotations

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#355]
As we've discussed elsewhere, it would be nice if we could consolidate our "proofreading" body annotations with the "biology" body annotations, but simply storing all of it in clio-store.

In theory, we could simply require all clients to learn how to talk to clio-store directly (including NeuTu and various batch scripts).  But it might be more convenient if DVID could act as a proxy to clio-store.  To our clients, the details about how to fetch the right version of the body annotations (for a given UUID) would be hidden.  They'd just provide a UUID, a segmentation instance name, and a body ID.  They'd get a JSON document in response.

**Comment by DocSavage** [comment]
With the new neuronjson data type, DVID becomes the central store and clio-store will proxy to DVID.  Since DVID can run on larger centralized servers, we can also have in-memory annotations for "head" versions with slower disk access for non-head versions.
