### ISSUE TITLE
Mac builds are broken

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#357]
In addition to our other build system woes, I just discovered that our Mac builds for v0.9.9, v0.9.10, and v0.9.11 are all broken.  The executable can't be launched, failing with the following message:

```
dyld: malformed mach-o image: segment __DWARF has vmsize < filesize
```

v0.9.8 does work, though.

**Comment by DocSavage** [comment]
We should revisit this given new module-aware builds and upgrade to Go.

**Comment by stuarteberg** [comment]
Indeed, this seems to be fixed in newer builds.
