### ISSUE TITLE
unable to restart dvid (unable to initialize storage)

### ISSUE THREAD

**Issue by FeifeiyuM** [janelia-flyem/dvid#368]
This is happened at the time of loading images。

Restart Command: 

$ dvid -verbose serve config.toml

Error: 
tomlConfig Auth: {   false}
Sending log messages to: /tmp/dvid/dvid.log
unable to initialize storage: bad store "raid6": Corruption: truncated record at end of file

log:
 INFO No authorization file found.  Proceeding without authorization.
 INFO backend.KVStore[default] = raid6
 INFO Found log at /tmp/dvid/mutation (err = <nil>)
 INFO 2022/04/13 09:30:51 Found directory at /data/dvid/database (err = <nil>)
 INFO 2022/04/13 09:30:51 leveldb cache size: 537MB
 DEBUG 2022/04/13 09:30:51 LRU cache size set to 536870912 bytes.
 INFO 2022/04/13 09:30:51 leveldb write buffer size: 63MB
 DEBUG 2022/04/13 09:30:51 Write buffer set to 62914560 bytes.
 DEBUG 2022/04/13 09:30:51 Block size set to 65536 bytes.
 INFO 2022/04/13 09:30:51 Opening basholeveldb @ path /data/dvid/database

DVID limit the size of images that loaded to it ?

**Comment by DocSavage** [comment]
No, DVID can handle TBs in a dataset.  This might be a DB corruption.  Was it working before and you have enough disk space for the mounted disk for /tmp?

You could try the repair command:
https://github.com/janelia-flyem/dvid/blob/master/cmd/dvid/main.go#L102
`$ dvid repair basholeveldb /tmp/dvid/dvid.log`

**Comment by FeifeiyuM** [comment]
> 
thankx.  /tmp is used for log file storage. disk space for images is enough.

**Comment by DocSavage** [comment]
Did the "repair" command fix your problem?
If the basholeveldb engine isn't working for your setup, there are other engines you could try like "badger" (either badger v2 on master branch or badger v3 on the badger-v3 branch).

**Comment by FeifeiyuM** [comment]
> Did the "repair" command fix your problem? If the basholeveldb engine isn't working for your setup, there are other engines you could try like "badger" (either badger v2 on master branch or badger v3 on the badger-v3 branch).

It's worked. thanx
