### ISSUE TITLE
max versions limited to ~256

### ISSUE THREAD

**Issue by pgunn** [janelia-flyem/dvid#371]
Right now the max length of a version chain is, I believe, 256. Going over this is not supported. (we talked about this on a zoom call)

**Comment by DocSavage** [comment]
This has been tested using the merge / cleave and other labelmap unit tests, including a new one for the new low-level in-memory map. The in-memory mapping system now handles uint32 version IDs (current DVID max).  There have been a few improvements to the system: 
- now using varints for version IDs and mapped labels, so if labels are not using full 8 bytes for uint64, will compress.
- the mapping lookup should be faster at O(N) where N is just the # of versions of a particular label's mapping

If this passes real-world stress testing, I'll close the issue.

**Comment by DocSavage** [comment]
This should be usable now as of commit 5dbdae2
