### ISSUE TITLE
Disable labelmap endpoint: /split

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#381]
We should not be using `/split` any more.  It looks like it was accidentally used (one time) on our production repo.  This should not have happened, but since the software permits it, we're exposed to it.

Just to be clear, I'm talking about body splits:

```
POST <api URL>/node/<UUID>/<data name>/split/<label>
```

**Comment by DocSavage** [comment]
Simply removing it might break others' systems. We could just add a flag that ignores the /split endpoint.

**Comment by DocSavage** [comment]
Fixed via configuration option in commit 3199c84.
