### ISSUE TITLE
Not able to start the server and webpage

### ISSUE THREAD

**Issue by leosv123** [janelia-flyem/dvid#388]
I have downloaded all the datasets in a virtual machine in Google cloud. 
I followed the instructions given in https://dvid.io/docs/hemibrain/
I am currently using 2TB HDD for storing. 

On trying to run hemibrain-dvid/hemibrain-release.toml file

I get these messages and terminates without any error log:

`Sending log messages to: /tmp/hemibrain-release.log
badger 2023/11/08 21:29:01 INFO: All 3 tables opened in 893ms
badger 2023/11/08 21:29:01 INFO: Replaying file id: 37 at offset: 13782940
badger 2023/11/08 21:29:01 INFO: Replay took: 14.884µs
badger 2023/11/08 21:29:01 DEBUG: Value log discard stats empty
badger 2023/11/08 21:29:03 INFO: All 2 tables opened in 330ms
badger 2023/11/08 21:29:03 INFO: Replaying file id: 15 at offset: 48366317
badger 2023/11/08 21:29:03 INFO: Replay took: 11.223µs
badger 2023/11/08 21:29:03 DEBUG: Value log discard stats empty
badger 2023/11/08 21:29:03 INFO: All 1 tables opened in 20ms
badger 2023/11/08 21:29:03 INFO: Replaying file id: 143 at offset: 806069901
badger 2023/11/08 21:29:03 INFO: Replay took: 14.141µs
badger 2023/11/08 21:29:03 DEBUG: Value log discard stats empty
Launching sync event handler for data "synapses_labelsz"...`

Not able to see the webpage and getting terminated in the console after 2 minutes

I am using the toml file:

`
# The FlyEM hemibrain (except grayscale)

[server]
httpAddress = "xx.xx.xxx.xx:8000"
rpcAddress = "xx.xx.xxx.xx:8001"
webClient = "./http/dvid-console"
corsDomains = ["janelia.org"]

[logging]
logfile = "/tmp/hemibrain-release.log"
max_log_size = 500 # MB
max_log_age = 360   # days

[mutations]
logstore = "mutationlog"
blobstore = "blobstore"

#[kafka]
#topicPrefix = "dvidactivity-reconstruction"
#servers = ["kafka.int.janelia.org:9092", "kafka2.int.janelia.org:9092", "kafka3.int.janelia.org:9092"]
#bufferSize = 1000000  # max messages in queue, default was 100,000

[backend]
    [backend.metadata]
    store = "metadata"

    [backend."segmentation:28841c8277e044a7b187dda03e18da13"]
    store = "segmentation"
    log = "mutationlog"

    [backend."synapses:28841c8277e044a7b187dda03e18da13"]
    store = "synapses"
    log = "mutationlog"

    [backend."synapses_labelsz:28841c8277e044a7b187dda03e18da13"]
    store = "synapses"
    log = "mutationlog"

    [backend."segmentation_meshes:28841c8277e044a7b187dda03e18da13"]
    store = "meshes"
    log = "mutationlog"

    [backend.labelmap]
    store = "labelmaps"
    log = "mutationlog"

    [backend.annotations]
    store = "annotations"
    log = "mutationlog"

    [backend.keyvalue]
    store = "keyvalues"
    log = "mutationlog"

    [backend.roi]
    store = "rois"
    log = "mutationlog"

    [backend.default]
    store = "misc"
    log = "mutationlog"

[store]
    [store.metadata]
    engine = "basholeveldb"
    path = "../databases/metadata"

    [store.segmentation]
    engine = "basholeveldb"
    path = "../databases/segmentation"

    [store.labelmaps]
    engine = "basholeveldb"
    path = "../databases/other-labelmaps"

    [store.synapses]
    engine = "basholeveldb"
    path = "../databases/synapses"

    [store.annotations]
    engine = "basholeveldb"
    path = "../databases/annotations"

    [store.meshes]
    engine = "badger"
    path = "../databases/meshes"

    [store.keyvalues]
    engine = "badger"
    path = "../databases/keyvalues"

    [store.rois]
    engine = "badger"
    path = "../databases/rois"

    [store.mutationlog]
    engine = "filelog"
    path = "../databases/mutlog"

    [store.misc]
    engine = "basholeveldb"
    path = "../databases/extra"
`

May i know what is wrong in this

**Comment by DocSavage** [comment]
Hi, could you attach the full log or send it via email? Typically the server will eventually reach the end of initialization (after seconds to minutes depending on size of datasets and mutations) and say it's now running the HTTP API at a chosen port (8000 by your TOML above). Also, it would be good to know the OS and size of the VM instance you were running.

**Comment by DocSavage** [comment]
I'm closing but feel free to reopen if it's still not working and you have the startup log.
