### ISSUE TITLE
Add ability to see disk usage of each instance

### ISSUE THREAD

**Issue by gregpinero** [janelia-flyem/dvid#62]
Problem:  There's no way to know how much disk space each instance is using.  This makes it difficult to manage the server.

(Ideally this would be shown on the web console next to the instance.)
Another option that would be simpler is to simply print out the sizes of each instance into the log when DVID starts up.

**Comment by DocSavage** [comment]
While this would be simple in a single server DVID frontend by adding some mutable properties to the data instance map, it becomes more troublesome for distributed DVID frontends.  Disk usage is best handled at the storage engine level and is database-specific.  I'll add a Sizer interface to the storage package that returns an exact or approximate (in leveldb case) size for a given data instance.  Then expose this via an api that will either return the size or if the storage engine doesn't support sizing, a status code 404.
