### ISSUE TITLE
UUIDs too similar

### ISSUE THREAD

**Issue by stephenplaza** [janelia-flyem/dvid#69]
When I create repos with similar names the UUIDs are very similar.  The first several characters are often identical making it annoying for clients that often treat the first several characters as generally unique.

**Comment by DocSavage** [comment]
The current UUID library uses version 1 UUIDs (MAC address and date-time, see [wikipedia UUID article](http://en.wikipedia.org/wiki/Universally_unique_identifier)).  If the UUIDs are generated quickly in succession, the first hexadecimals may be similar.

Solution is to go to a better library.  I plan on swapping in [this library that supports version 4 UUIDs](https://github.com/twinj/uuid), which are randomly generated.  Eventually, we should also add some content-based hash like the non-cryptographic murmur3 as a checksum and way of looking up repos based on a data signature, e.g., find the repo that has a grayscale volume at time X.
