### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by tartavull** [janelia-flyem/dvid#70]
While trying to install I get this error:

	 make dvid
	[ 23%] Built target golang-1.4.2
	[ 26%] Compiling and installing dvid backup command...
	command-line-arguments
	[ 26%] Built target dvid-backup
	[ 28%] Adding go package dependencies for janelia-flyem projects...
	[ 28%] Built target gopackages-install
	[ 31%] Updating required Go packages...
	[ 31%] Built target gopackages
	[ 34%] Building nrsc resource compiler...
	[ 34%] Built target nrsc
	[ 55%] Built target dvid-console
	[ 84%] Built target basholeveldb-1.9
	[ 86%] Adding gojsonschema library...
	[ 86%] Built target gojsonschema
	[ 89%] Adding lumberjack library...
	[ 89%] Built target lumberjack
	[ 92%] Adding go.net context
	[ 92%] Built target context
	[ 94%] Adding goji web routing library...
	[ 94%] Built target goji
	[ 97%] Compiling and installing dvid executable...
	github.com/janelia-flyem/go/freetype-go/freetype/raster
	github.com/janelia-flyem/go/freetype-go/freetype/truetype
	github.com/janelia-flyem/go/go-uuid/uuid
	github.com/janelia-flyem/go/go.image/bmp
	github.com/janelia-flyem/go/go.image/tiff/lzw
	github.com/janelia-flyem/go/golz4
	github.com/janelia-flyem/go/snappy-go/snappy
	github.com/janelia-flyem/go/basholeveldb
	github.com/janelia-flyem/go/go-humanize
	github.com/janelia-flyem/go/go.image/tiff
	github.com/janelia-flyem/go/nrsc
	github.com/janelia-flyem/go/toml
	github.com/janelia-flyem/go/freetype-go/freetype
	# github.com/janelia-flyem/go/basholeveldb
	/usr/people/it2/buildem/lib/libleveldb.so: undefined reference to `snappy::RawUncompress(char const*, unsigned long, char*)'
	/usr/people/it2/buildem/lib/libleveldb.so: undefined reference to `snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)'
	/usr/people/it2/buildem/lib/libleveldb.so: undefined reference to `snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)'
	/usr/people/it2/buildem/lib/libleveldb.so: undefined reference to `snappy::MaxCompressedLength(unsigned long)'
	collect2: error: ld returned 1 exit status
	github.com/janelia-flyem/dvid/dvid
	# github.com/janelia-flyem/dvid/dvid
	dvid/data.go:67: undefined: uuid.NewUUID
	make[3]: *** [CMakeFiles/dvid-exe] Error 2
	make[2]: *** [CMakeFiles/dvid-exe.dir/all] Error 2
	make[1]: *** [CMakeFiles/dvid.dir/rule] Error 2
	make: *** [dvid] Error 2

What could I be doing wrong?

**Comment by DocSavage** [comment]
Sorry, this looks like some changes we made to the supporting janelia-flyem/go repo for our "refactor" branch that inadvertently broke the master branch.  We switched from go-uuid to twinj/uuid:

I think this might work:

     % cd $GOPATH/src/github.com/janelia-flyem/go
     % git checkout 5658c3e1

Then do the make again.  If that doesn't work, I can re-add go-uuid to the supporting repo.  We plan on merging changes from refactor branch to master pretty soon, but it will also require updating the wiki and supporting documents.

**Comment by tartavull** [comment]
I greatly appreciate your support Bill.
I tried what you said. But It failed to find the uuid folder
```	➜  build git:(master) make dvid
	[ 23%] Built target golang-1.4.2
	[ 26%] Compiling and installing dvid backup command...
	command-line-arguments
	[ 26%] Built target dvid-backup
	[ 28%] Adding go package dependencies for janelia-flyem projects...
	[ 28%] Built target gopackages-install
	[ 31%] Updating required Go packages...
	Submodule path 'murmur3': checked out '9d87265e0948d305ffe0383d54e59c3ac3482454'
	Submodule path 'uuid': checked out '4d772442af203e27723acc7d1eea6c93cd319c57'
	[ 31%] Built target gopackages
	[ 34%] Building nrsc resource compiler...
	[ 34%] Built target nrsc
	[ 55%] Built target dvid-console
	[ 84%] Built target basholeveldb-1.9
	[ 86%] Adding gojsonschema library...
	[ 86%] Built target gojsonschema
	[ 89%] Adding lumberjack library...
	[ 89%] Built target lumberjack
	[ 92%] Adding go.net context
	[ 92%] Built target context
	[ 94%] Adding goji web routing library...
	[ 94%] Built target goji
	[ 97%] Compiling and installing dvid executable...
	dvid/data.go:11:2: cannot find package "github.com/janelia-flyem/go/go-uuid/uuid" in any of:
		/usr/people/it2/buildem/src/golang-1.4.2/src/github.com/janelia-flyem/go/go-uuid/uuid (from $GOROOT)
		/usr/people/it2/go/src/github.com/janelia-flyem/go/go-uuid/uuid (from $GOPATH)
	make[3]: *** [CMakeFiles/dvid-exe] Error 1
	make[2]: *** [CMakeFiles/dvid-exe.dir/all] Error 2
	make[1]: *** [CMakeFiles/dvid.dir/rule] Error 2
	make: *** [dvid] Error 2
```
I solved this by copying the folder from  "github.com/janelia-flyem/go/uuid" to  "github.com/janelia-flyem/go/go-uuid/uuid"
After doing so, I get exactly the same error as in my first message.

I wanted to try dvid because it sounds very interested, but I'm not in a rush. I can wait until your merged.

Thanks,
   Ignacio

**Comment by DocSavage** [comment]
Rather than wait for refactor branch, I just re-added the go-uuid package to github.com/janelia-flyem/go repo.
