### ISSUE TITLE
DVID HEAD support

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/dvid#75]
This will allow a client to quickly check whether some data exists or not. The HEAD method will be particularly helpful for checking data potentially with large size. If it cannot be implemented for all endpoints, there should be some way for a client to know which endpoints  have HEAD and which do not.

**Comment by DocSavage** [comment]
If you simply call HEAD on an endpoint and it returns a http status code 405 (method not accepted) you'll know HEAD is not accepted.  I can also add "Access-Control-Allow-Methods" to response giving the accepted methods like GET.

**Comment by DocSavage** [comment]
Added HEAD for sparsevol presence check in commit a41df47a8d.

**Comment by DocSavage** [comment]
Closing for now.  Reopen with particular datatype you want to support HEAD actions.

**Comment by DocSavage** [comment]
Should also reopen this to support HEAD for keyvalue as well.

**Comment by DocSavage** [comment]
Example from log:

`2016/11/14 14:12:55 [c06u27.int.janelia.org/H7Tfo4yxmN-20477553] Started GET "/api/node/005a/segmentation-labelvol_annotations/key/72323806?u=zhaot&app=NeuTu" from 10.101.10.201:35252`

This returns a 404 but would return full contents although Ting just wants whether it exists.

**Comment by DocSavage** [comment]
Was fixed in commit 940569a44e0352615418f9a265ffa4419b6cdae6
