### ISSUE TITLE
Split body from bounding box

### ISSUE THREAD

**Issue by stephenplaza** [janelia-flyem/dvid#81]
It should be possible to split a body based on bounding box information (ideally it does not have to be block aligned).  Currently, DVID allows one to fetch a sparse volume within a bounding box.  It should be possible to say that this region should be split from the main body instead of fetched.

**Comment by DocSavage** [comment]
Is this API still needed now that we have coarse splits enabled?  I can see how a bounding box is simpler to send and obtain on the client side rather than a list of blocks.

**Comment by DocSavage** [comment]
Closing for now since we have split-coarse endpoint.
