### ISSUE TITLE
API for storage engines

### ISSUE THREAD

**Issue by jjpepper** [janelia-flyem/dvid#83]
Hi, I'm wondering what is the API to storage engines at the backend?  

My colleagues and I have developed very data store that offers very high ingestion rates and transaction rates.  We are considering open sourcing (dual-licensing) the library and wonder if your project may benefit.

It features atomic transactions, automatic crash recovery, incremental backup, slave mirroring, optional transaction durability and concurrent reading with writing.  The keys are always 64 bit integers and mapped values are read or written as arbitrary length serial byte streams.  High performance general purpose hash maps, B+Trees, lists and other data structures are built on top of the storage engine. 

Features include:
C++ interface
Portable, builds in Linux/Windows/Mac OSX
Ability to "tune" for specific hardware
Very high transaction throughput
Excellent read & write performance (typically IO bound)
Transactional data storage
Recovery scan (roll forward) after non-graceful shutdown
Automatic cleaning ensures disk space is well utilised
Supports concurrent access by multiple threads
Transaction logging feature facilitates live backup of data

From some RAM disk testing:
Test hardware:
Intel Core i5-3570K @ 3.40-3.80 GHz. 8GB RAM. 
Windows 7 64 bit. 
Dataram 512MB RAM disk, format NTFS.
Write performance characteristics.
Max data rate is about 3.1 GB/s
Max serial element rate (rate to write key/value pairs) is about 2.8 MHz .
Max txn rate is about 2.2 MHz.

Are you interested?  Please contact at jesse.pepper@thinkbottomup.com.au if so.

Regards,
Jesse

**Comment by DocSavage** [comment]
The basic storage engine API is here:

https://github.com/janelia-flyem/dvid/blob/master/storage/storage.go#L184

Most of the data types require an OrderedKeyValueDB.  Some of them also require the ability to do batch transactions.

The main issue with using your database is the 64-bit integer keys.  DVID (and many other apps relying on key-value stores) requires arbitrary length (up to a modest size) binary keys.  To use your database, we'd have to create a mapping layer.

**Comment by jjpepper** [comment]
We have a key-value pair store in a layer on top already but haven't
packaged it up yet.  It performs very well.

Could you conjure up a simple benchmark (say - just guessing at your usage
- storing random key-value pairs, with keys between 8 bytes and 2048
bytes and values between 2MB and 20MB) with some corresponding performance
metrics that your fastest storage engine can provide, for us to do a
comparison. If our results were significantly better, say >20%, you'd be
compelled to use our store.

Are your typical applications more concerned with streamed writes, or is
writing rare and reads are the main concern (or is usage not really
dominated by either).

On Friday, May 22, 2015, Bill Katz <notifications@github.com> wrote:

> The basic storage engine API is here:
>
> https://github.com/janelia-flyem/dvid/blob/master/storage/storage.go#L184
>
> Most of the data types require an OrderedKeyValueDB. Some of them also
> require the ability to do batch transactions.
>
> The main issue with using your database is the 64-bit integer keys. DVID
> (and many other apps relying on key-value stores) requires arbitrary length
> (up to a modest size) binary keys. To use your database, we'd have to
> create a mapping layer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/janelia-flyem/dvid/issues/83#issuecomment-104394628>.
>


-- 
Jesse Pepper

Director

Think Bottom Up Pty Ltd

e: jesse.pepper@thinkbottomup.com.au
m: +61 4 2467 5865
t: +61 8 6460 1643
f: +61 8 6210 1175
16/9 Vale St, Malaga,
Western Australia 6090

**Comment by DocSavage** [comment]
We are severely constrained right now in terms of our manpower to tune the storage engine and perform benchmarks.  Right now, embedded basho-tuned leveldb is working for us, but we definitely plan on exploring more backends including some combination of data stores that we can't really talk about right now.

Benchmarking in general is difficult because there is a large and growing API across diverse data types, each of which have different usage patterns (read/write mix and size of payloads).  Also, whether we go with a particular backend is much more than benchmarking.  Off the top of my head it includes things like: (1) licensing, (2) community, (3) ability to hack on it to adapt to potentially future needs, i.e., open source and how facile we are in the language/tech stack, (4) write amplification, (5) immutable vs mutable performance and $$/TB for each.

**Comment by jjpepper** [comment]
Hi Bill,
Sorry for the delay and thanks for taking the time to get back to me.  I
should mention that I came across your project via the LMDB site.  We're
thinking we'd probably be a great match for anyone thinking of using their
DB.

Regarding your points 1-5:

1) Do you mean in terms of restrictions?
2) Understood.  That, of course, we don't have (at the moment) while we're
still closed source.
3) Yes, we are planning to open source.
4) The structure of our store suffers very little from write
amplification... in fact it's hard to imagine another database behaving as
well as ours in this regard.
5) Our store performs very well at both reading and writing, it's generally
IO bound.
6) Not sure what you mean?  Our store does not need write ahead logging,
and as such is very compact on disk, disk wastage factors are very very
small.

This thread on the berkeley DB forums
<https://community.oracle.com/message/13060218#13060218> gives some
indications of our performance for inserting key-value pairs into the
database.  Keep us in mind, and if you have more questions, please ask.

Regards,
Jesse

On Fri, May 22, 2015 at 4:47 AM, Bill Katz <notifications@github.com> wrote:

> We are severely constrained right now in terms of our manpower to tune the
> storage engine and perform benchmarks. Right now, embedded basho-tuned
> leveldb is working for us, but we definitely plan on exploring more
> backends including some combination of data stores that we can't really
> talk about right now.
>
> Benchmarking in general is difficult because there is a large and growing
> API across diverse data types, each of which have different usage patterns
> (read/write mix and size of payloads). Also, whether we go with a
> particular backend is much more than benchmarking. Off the top of my head
> it includes things like: (1) licensing, (2) community, (3) ability to hack
> on it to adapt to potentially future needs, i.e., open source and how
> facile we are in the language/tech stack, (4) write amplification, (5)
> immutable vs mutable performance and $$/TB for each.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/janelia-flyem/dvid/issues/83#issuecomment-104416192>.
>



-- 
Jesse Pepper

Director

Think Bottom Up Pty Ltd

e: jesse.pepper@thinkbottomup.com.au
m: +61 4 2467 5865
t: +61 8 6460 1643
f: +61 8 6210 1175
16/9 Vale St, Malaga,
Western Australia 6090
