### ISSUE TITLE
sparse volume query within z range

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/dvid#90]
Example: http://emdata1.int.janelia.org:8500/api/node/86e1/bodies/sparsevol/15294484?minz=7317&maxz=7317 
returns 32 slices (7296-7327) instead of one.

**Comment by DocSavage** [comment]
The API now returns exact voxel bounds by default.  Before "exact=false" was the default option unless you specified "exact=true".  Now, you have to specify "exact=false" for performance increase, so it's slower by default.
